### PR TITLE
Add Make version 4.1

### PR DESCRIPTION
**Pull request by phil-blain**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by phil-blain** [comment]
Hi @conda-forge/core, not sure what is wrong here... I did the same changes as my precedent PR  (#16) and on this one the re-rendering does not seem to work.

**Comment by phil-blain** [comment]
I found some errors in the Azure linux_ build log, at the test stage:
```shell
features/archives ....................................... FAILED (4/10 passed)`
[...]
Test timed out after 5 seconds

Caught signal 14!
misc/fopen-fail ......................................... Error running $SRC_DIR/tests/../make (expected 512; got 14): $SRC_DIR/tests/../make -f work/misc/fopen-fail.mk
FAILED (0/1 passed)
[...]
7 Tests in 2 Categories Failed (See .diff* files in work dir for details) :-(
```
and a different error in the linux_ppc64le_ build:
```shell
misc/fopen-fail ......................................... Error running $SRC_DIR/tests/../make (expected 512; got 14): $SRC_DIR/tests/../make -f work/misc/fopen-fail.mk

Test timed out after 5 seconds

Caught signal 14!
FAILED (0/1 passed)
```

the windows build have
```shell
(%BUILD_PREFIX%) %SRC_DIR%>copy .\\GccRel\\gnumake.exe  %PREFIX%\Library\bin\\gnumake.exe 
The system cannot find the path specified.
```

**Comment by scopatz** [comment]
hmm weird

**Comment by phil-blain** [comment]
I rerendered locally using conda smithy, but the CI still fails...

**Comment by scopatz** [comment]
you might need to look at the log to see the actual error

**Comment by phil-blain** [comment]
I'll close this as I don't need older versions of Make anymore.

**Pull request closed without merging**
