### PR TITLE
aarch64 rebuild.

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by scopatz** [comment]
Wait weird, the details link still goes to the check page?!

**Comment by mariusvniekerk** [comment]
Might be a slow rollout?

**Comment by scopatz** [comment]
This LGTM.  Will merge after it passes

**Comment by scopatz** [comment]
Or you can too, if you want

**Comment by asmeurer** [comment]
To make Azure not go to the checks page, you have to enable it using oauth. If you enable it using GitHub apps, it goes to the checks page (my understanding is that this is a limitation of GitHub apps).

**Comment by scopatz** [comment]
interesting.

**Pull request merged**
